/**
 * Created by sbv23 on 26/03/2017.
 */
module.exports = {
    query_validateRegister: "SELECT PK_SENSOR FROM TBL_SENSOR WHERE SERIAL_SENSOR = '${serial}' AND STATUS_SENSOR = 'Activo'",
    query_insertSensor: "INSERT INTO TBL_SENSOR (SERIAL_SENSOR, PK_NETWORK, NAME_SENSOR, STATUS_SENSOR, REGISTERDATE_SENSOR, UPDATEDATE_SENSOR) VALUES ('${serial}', ${network}, '${name}', 'Activo', '${date1}', '${date2}')",
    query_updateSensor: "UPDATE TBL_SENSOR SET STATUS_SENSOR = 'Inactivo', UPDATEDATE_SENSOR = '${date}' WHERE PK_SENSOR = ${pk_sensor}",
    query_verifyUploadPath: "SELECT count(*) AS counter FROM TBL_LOCATION WHERE UPLOADPATH_LOCATION = '${uploadPath}'",
    query_verifyRegisterLocation: "SELECT count(*) AS counter FROM TBL_LOCATION WHERE PK_SENSOR = ${pk_sensor}",
    query_getUploadPathNetwork: "SELECT UPLOADPATH_NETWORK FROM TBL_SENSOR INNER JOIN TBL_NETWORK ON TBL_SENSOR.PK_NETWORK = TBL_NETWORK.PK_NETWORK WHERE PK_SENSOR = ${pk_sensor}",
    query_insertLocation: "INSERT INTO TBL_LOCATION (PK_SENSOR, LAT_LOCATION, LNG_LOCATION, ALT_LOCATION, ADDRESS_LOCATION, REGISTERDATE_LOCATION, UPDATEDATE_LOCATION, UPLOADPATH_LOCATION) VALUES (${pk_sensor},'${lat}','${lng}','${alt}','${address}','${date1}','${date2}','${uploadpath}')",
    query_insertFile: "INSERT INTO TBL_FILE (PK_SENSOR, PATH_FILE, DATE_FILE, HOUR_FILE, REGISTERDATE_FILE, PK_LOCATION, AXIS_FILE) VALUES (${pk_sensor},'${path_file}', '${date}', '${hour}', '${reg_date}', ${pk_location},'${axis}')",
    query_verifyExistFile: "SELECT count(tbf.PK_FILE) AS counter, (SELECT tbl.UPLOADPATH_LOCATION FROM TBL_LOCATION tbl WHERE tbl.PK_SENSOR = ${pk_sensor} AND tbl.STATUS_LOCATION = 'Activa') as UPLOADPATH, (SELECT tbl2.PK_LOCATION FROM TBL_LOCATION tbl2 WHERE tbl2.PK_SENSOR = ${pk_sensor} AND tbl2.STATUS_LOCATION = 'Activa') as PK_LOCATION FROM TBL_FILE tbf WHERE tbf.PK_SENSOR = ${pk_sensor} AND tbf.DATE_FILE = '${date}' AND tbf.HOUR_FILE = '${hour}' AND tbf.AXIS_FILE = '${axis}'",
    query_updateFile: "UPDATE TBL_FILE SET PATH_FILE = '${path_file}', REGISTERDATE_FILE = '${reg_date}' WHERE PK_SENSOR = ${pk_sensor} AND DATE_FILE = '${date}' AND HOUR_FILE = '${hour}' AND AXIS_FILE = '${axis}'",
    query_updateLocations: "UPDATE TBL_LOCATION SET STATUS_LOCATION = 'Inactiva', UPDATEDATE_LOCATION = '${date}' WHERE PK_SENSOR = ${pk_sensor}",
    query_verifyAcc: "SELECT count(*) AS counter FROM TBL_ACCELEROMETER WHERE PK_SENSOR = ${pk_sensor}",
    query_registerAcc: "INSERT INTO TBL_ACCELEROMETER (PK_SENSOR, STATUS_ACCELEROMETER, DESCRIPT_ACCELEROMETER, ERROR_ACCELEROMETER, UPDATEDATE_ACCELEROMETER) VALUES (${pk_sensor},'${status}','${descript}','${error}','${date}')",
    query_updateAcc: "UPDATE TBL_ACCELEROMETER SET STATUS_ACCELEROMETER = '${status}', DESCRIPT_ACCELEROMETER = '${descript}', ERROR_ACCELEROMETER = '${error}', UPDATEDATE_ACCELEROMETER = '${date}' WHERE PK_SENSOR = ${pk_sensor}",
    query_getAcc: "SELECT STATUS_ACCELEROMETER, DESCRIPT_ACCELEROMETER, ERROR_ACCELEROMETER FROM TBL_ACCELEROMETER WHERE PK_SENSOR = ${pk_sensor}",
    query_verifyAdc: "SELECT count(*) AS counter FROM TBL_ADC WHERE PK_SENSOR = ${pk_sensor}",
    query_registerAdc: "INSERT INTO TBL_ADC (PK_SENSOR, STATUS_ADC, DESCRIPT_ADC, SAMPLES_ADC, ERROR_ADC, UPDATEDATE_ADC) VALUES (${pk_sensor},'${status}','${descript}','${samples}','${error}','${date}')",
    query_updateAdc: "UPDATE TBL_ADC SET STATUS_ADC = '${status}', DESCRIPT_ADC = '${descript}', SAMPLES_ADC = '${samples}', ERROR_ADC = '${error}', UPDATEDATE_ADC = '${date}' WHERE PK_SENSOR = ${pk_sensor}",
    query_getAdc: "SELECT STATUS_ADC, DESCRIPT_ADC, SAMPLES_ADC, ERROR_ADC FROM TBL_ADC WHERE PK_SENSOR = ${pk_sensor}",
    query_verifyBat: "SELECT count(*) AS counter FROM TBL_BATTERY WHERE PK_SENSOR = ${pk_sensor}",
    query_registerBat: "INSERT INTO TBL_BATTERY (PK_SENSOR, STATUS_BATTERY, DESCRIPT_BATTERY, CHARGE_BATTERY, ERROR_BATTERY, UPDATEDATE_BATTERY) VALUES (${pk_sensor},'${status}','${descript}',${charge},'${error}','${date}')",
    query_updateBat: "UPDATE TBL_BATTERY SET STATUS_BATTERY = '${status}', DESCRIPT_BATTERY = '${descript}', CHARGE_BATTERY = ${charge}, ERROR_BATTERY = '${error}', UPDATEDATE_BATTERY = '${date}' WHERE PK_SENSOR = ${pk_sensor}",
    query_getBat: "SELECT STATUS_BATTERY, DESCRIPT_BATTERY, CHARGE_BATTERY, ERROR_BATTERY FROM TBL_BATTERY WHERE PK_SENSOR = ${pk_sensor}",
    query_verifyCpu: "SELECT count(*) AS counter FROM TBL_CPU WHERE PK_SENSOR = ${pk_sensor}",
    query_registerCpu: "INSERT INTO TBL_CPU (PK_SENSOR, STATUS_CPU, DESCRIPT_CPU, ERROR_CPU, UPDATEDATE_CPU) VALUES (${pk_sensor},'${status}','${descript}','${error}','${date}')",
    query_updateCpu: "UPDATE TBL_CPU SET STATUS_CPU = '${status}', DESCRIPT_CPU = '${descript}', ERROR_CPU = '${error}', UPDATEDATE_CPU = '${date}' WHERE PK_SENSOR = ${pk_sensor}",
    query_getCpu: "SELECT STATUS_CPU, DESCRIPT_CPU, ERROR_CPU FROM TBL_CPU WHERE PK_SENSOR = ${pk_sensor}",
    query_verifyGps: "SELECT count(*) AS counter FROM TBL_GPS WHERE PK_SENSOR = ${pk_sensor}",
    query_registerGps: "INSERT INTO TBL_GPS (PK_SENSOR, STATUS_GPS, DESCRIPT_GPS, BAUDRATE_GPS, MSJNMEA, ERROR_GPS, UPDATEDATE_GPS) VALUES (${pk_sensor},'${status}','${descript}',${baudRate},'${msjNMEA}','${error}','${date}')",
    query_updateGps: "UPDATE TBL_GPS SET STATUS_GPS = '${status}', DESCRIPT_GPS = '${descript}', BAUDRATE_GPS = ${baudRate}, MSJNMEA = '${+msjNMEA}', ERROR_GPS = '${error}', UPDATEDATE_GPS = '${date}' WHERE PK_SENSOR = ${pk_sensor}",
    query_getGps: "SELECT STATUS_GPS, DESCRIPT_GPS, BAUDRATE_GPS, MSJNMEA, ERROR_GPS FROM TBL_GPS WHERE PK_SENSOR = ${pk_sensor}",
    query_verifyRtc: "SELECT count(*) AS counter FROM TBL_RTC WHERE PK_SENSOR = ${pk_sensor}",
    query_registerRtc: "INSERT INTO TBL_RTC (PK_SENSOR, STATUS_RTC, DESCRIPT_RTC, DATEHOUR_RTC, ERROR_RTC, UPDATEDATE_RTC) VALUES (${pk_sensor},'${status}','${descript}','${dateHour}','${error}','${date}')",
    query_updateRtc: "UPDATE TBL_RTC SET STATUS_RTC = '${status}', DESCRIPT_RTC = '${descript}', DATEHOUR_RTC = '${dateHour}', ERROR_RTC = '${error}', UPDATEDATE_RTC = '${date}' WHERE PK_SENSOR = ${pk_sensor}",
    query_getRtc: "SELECT STATUS_RTC, DESCRIPT_RTC, DATEHOUR_RTC, ERROR_RTC FROM TBL_RTC WHERE PK_SENSOR = ${pk_sensor}",
    query_verifyWifi: "SELECT count(*) AS counter FROM TBL_WIFI WHERE PK_SENSOR = ${pk_sensor}",
    query_registerWifi: "INSERT INTO TBL_WIFI (PK_SENSOR, STATUS_WIFI, DESCRIPT_WIFI, SSID_WIFI, IPADR_WIFI, MACADR_WIFI, ERROR_WIFI, UPDATEDATE_WIFI) VALUES (${pk_sensor},'${status}','${descript}','${ssid}','${ipAdr}','${macAdr}','${error}','${date}')",
    query_updateWifi: "UPDATE TBL_WIFI SET STATUS_WIFI = '${status}', DESCRIPT_WIFI = '${descript}', SSID_WIFI = '${ssid}', IPADR_WIFI = '${ipAdr}', MACADR_WIFI = '${macAdr}', ERROR_WIFI = '${error}', UPDATEDATE_WIFI = '${date}' WHERE PK_SENSOR = ${pk_sensor}",
    query_getWifi: "SELECT STATUS_WIFI, DESCRIPT_WIFI, SSID_WIFI, IPADR_WIFI, MACADR_WIFI, ERROR_WIFI FROM TBL_WIFI WHERE PK_SENSOR = ${pk_sensor}"
};